package sanitize

// allowedCommands is the set of LaTeX commands permitted in expressions.
// Looked up without the leading backslash (e.g. "frac", not "\frac").
// "begin" and "end" are handled separately via allowedEnvironments.
var allowedCommands = map[string]bool{
	// Greek letters (lowercase)
	"alpha":      true,
	"beta":       true,
	"gamma":      true,
	"delta":      true,
	"epsilon":    true,
	"varepsilon": true,
	"zeta":       true,
	"eta":        true,
	"theta":      true,
	"vartheta":   true,
	"iota":       true,
	"kappa":      true,
	"lambda":     true,
	"mu":         true,
	"nu":         true,
	"xi":         true,
	"pi":         true,
	"varpi":      true,
	"rho":        true,
	"varrho":     true,
	"sigma":      true,
	"varsigma":   true,
	"tau":        true,
	"upsilon":    true,
	"phi":        true,
	"varphi":     true,
	"chi":        true,
	"psi":        true,
	"omega":      true,

	// Greek letters (uppercase)
	"Gamma":   true,
	"Delta":   true,
	"Theta":   true,
	"Lambda":  true,
	"Xi":      true,
	"Pi":      true,
	"Sigma":   true,
	"Upsilon": true,
	"Phi":     true,
	"Psi":     true,
	"Omega":   true,

	// Operators
	"frac":   true,
	"sqrt":   true,
	"sum":    true,
	"prod":   true,
	"int":    true,
	"iint":   true,
	"iiint":  true,
	"oint":   true,
	"lim":    true,
	"limsup": true,
	"liminf": true,
	"sup":    true,
	"inf":    true,
	"max":    true,
	"min":    true,
	"log":    true,
	"ln":     true,
	"exp":    true,
	"sin":    true,
	"cos":    true,
	"tan":    true,
	"cot":    true,
	"sec":    true,
	"csc":    true,
	"arcsin": true,
	"arccos": true,
	"arctan": true,
	"sinh":   true,
	"cosh":   true,
	"tanh":   true,
	"det":    true,
	"dim":    true,
	"ker":    true,
	"hom":    true,
	"arg":    true,
	"deg":    true,
	"gcd":    true,

	// Relations
	"leq":      true,
	"geq":      true,
	"neq":      true,
	"approx":   true,
	"equiv":    true,
	"sim":      true,
	"simeq":    true,
	"cong":     true,
	"propto":   true,
	"ll":       true,
	"gg":       true,
	"subset":   true,
	"supset":   true,
	"subseteq": true,
	"supseteq": true,
	"in":       true,
	"notin":    true,
	"ni":       true,
	"forall":   true,
	"exists":   true,
	"nexists":  true,

	// Arrows
	"rightarrow":      true,
	"leftarrow":       true,
	"leftrightarrow":  true,
	"Rightarrow":      true,
	"Leftarrow":       true,
	"Leftrightarrow":  true,
	"uparrow":         true,
	"downarrow":       true,
	"mapsto":          true,
	"implies":         true,
	"iff":             true,
	"to":              true,

	// Binary operators
	"pm":       true,
	"mp":       true,
	"times":    true,
	"div":      true,
	"cdot":     true,
	"ast":      true,
	"star":     true,
	"circ":     true,
	"bullet":   true,
	"oplus":    true,
	"otimes":   true,
	"odot":     true,
	"cap":      true,
	"cup":      true,
	"wedge":    true,
	"vee":      true,
	"setminus": true,

	// Delimiters
	"left":   true,
	"right":  true,
	"big":    true,
	"Big":    true,
	"bigg":   true,
	"Bigg":   true,
	"langle": true,
	"rangle": true,
	"lfloor": true,
	"rfloor": true,
	"lceil":  true,
	"rceil":  true,
	"lvert":  true,
	"rvert":  true,
	"lVert":  true,
	"rVert":  true,

	// Accents
	"hat":              true,
	"bar":              true,
	"tilde":            true,
	"vec":              true,
	"dot":              true,
	"ddot":             true,
	"overline":         true,
	"underline":        true,
	"widehat":          true,
	"widetilde":        true,
	"overrightarrow":   true,
	"overleftarrow":    true,

	// Font commands
	"mathrm":       true,
	"mathbf":       true,
	"mathit":       true,
	"mathsf":       true,
	"mathtt":       true,
	"mathcal":      true,
	"mathbb":       true,
	"mathfrak":     true,
	"text":         true,
	"textbf":       true,
	"textit":       true,
	"boldsymbol":   true,
	"operatorname": true,

	// Spacing
	"quad":      true,
	"qquad":     true,
	"enspace":   true,
	"thinspace": true,

	// Misc symbols
	"infty":       true,
	"partial":     true,
	"nabla":       true,
	"hbar":        true,
	"ell":         true,
	"Re":          true,
	"Im":          true,
	"wp":          true,
	"aleph":       true,
	"beth":        true,
	"emptyset":    true,
	"varnothing":  true,
	"cdots":       true,
	"ldots":       true,
	"vdots":       true,
	"ddots":       true,
	"prime":       true,
	"backprime":   true,
	"angle":       true,
	"triangle":    true,
	"square":      true,
	"diamond":     true,
	"clubsuit":    true,
	"diamondsuit": true,
	"heartsuit":   true,
	"spadesuit":   true,
	"flat":        true,
	"natural":     true,
	"sharp":       true,

	// Structural
	"binom":      true,
	"tbinom":     true,
	"dbinom":     true,
	"stackrel":   true,
	"overset":    true,
	"underset":   true,
	"underbrace": true,
	"overbrace":  true,
	"boxed":      true,
	"phantom":    true,
	"hphantom":   true,
	"vphantom":   true,
	"smash":      true,
	"not":        true,
	"mod":        true,
	"pmod":       true,
	"bmod":       true,

	// Other
	"color":   true,
	"cancel":  true,
	"xcancel": true,
	"sout":    true,
}

// allowedEnvironments is the set of environment names permitted with
// \begin{name} and \end{name}.
var allowedEnvironments = map[string]bool{
	"matrix":   true,
	"pmatrix":  true,
	"bmatrix":  true,
	"Bmatrix":  true,
	"vmatrix":  true,
	"Vmatrix":  true,
	"cases":    true,
	"aligned":  true,
	"gathered": true,
	"array":    true,
	"subarray": true,
	"split":    true,
}
